### ISSUE TITLE
Error on IntelliJ IDEA 2021.2.2 ClassCastException

### ISSUE THREAD

**Issue by lordigon** [leomillon/uuid-generator-plugin#98] opened 2021-10-08 07:45 UTC
After plugin upgrade I got this error

```
java.lang.ClassCastException: class com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings cannot be cast to class com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings (com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @28532a81; com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @63748042)
	at com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings$Companion.getInstance(UUIDGeneratorSettings.kt:44)
	at com.github.leomillon.uuidgenerator.annotator.uuid.UUIDDefaultAnnotator.annotate(UUIDAnnotator.kt:20)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.github.izhangzhihao.rainbow.brackets.visitor.RainbowHighlightVisitor.analyze(RainbowHighlightVisitor.kt:36)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by leomillon** [comment] 2021-10-08 08:17
Hi @lordigon ,

That's weird, I don't get this on IntelliJ 2021.2.2.

Could you please copy/past the detail of the IntelliJ version (in the "About" popup) you're using?

This should be something like this:

```
IntelliJ IDEA 2021.2.2 (Community Edition)
Build #IC-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Non-Bundled Plugins: com.github.leomillon.uuidgenerator (4.5.1)
Kotlin: 212-1.5.10-release-IJ5284.40
```

**Comment by lordigon** [comment] 2021-10-08 09:55
Hi Leo,
that' my IntelliJ IDEA version (where I deleted personal infos)

IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins: com.github.leomillon.uuidgenerator (4.5.1),
EclipseCodeFormatter (20.9.203.000.0-Eclipse_2020-06-JavaOnly), YourKit
Java Profiler 2020.9-b405 Integration (2020.9.405.0),
org.jetbrains.plugins.spotbugs (1.2.4), GenerateSerialVersionUID (3.0.3),
com.bluetrainsoftware.groovy.idea (1.0), MavenRunHelper (4.17.212.000.0),
org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7),
izhangzhihao.rainbow.brackets (6.21), GradleDependenciesHelper (1.16),
org.mapstruct.intellij (1.3.0), org.intellij.scala (2021.2.23)
Kotlin: 212-1.5.31-release-546-IJ4638.7

Il giorno ven 8 ott 2021 alle ore 10:17 Léo MILLON ***@***.***>
ha scritto:

**Comment by nessor** [comment] 2021-10-11 16:25
I'm getting also this error in WebStorm 2021.2.2:

```
java.lang.ClassCastException: class com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings cannot be cast to class com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings (com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2d6e6dd2; com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @48790c83)
	at com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings$Companion.getInstance(UUIDGeneratorSettings.kt:44)
	at com.github.leomillon.uuidgenerator.annotator.uuid.UUIDDefaultAnnotator.annotate(UUIDAnnotator.kt:20)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:114)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:605)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
=== About ===
Build version: WebStorm 2021.2.2 Build #WS-212.5284.41 September 14, 2021
Theme: Darcula
Java version: 11.0.12+7-b1504.28aarch64
Operating System: Mac OS X (11.6, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
idea.config.path=/Users/florian/Library/Application Support/JetBrains/WebStorm2021.2
idea.system.path=/Users/florian/Library/Caches/JetBrains/WebStorm2021.2
idea.plugins.path=/Users/florian/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-1/212.5284.41/WebStorm.app.plugins
idea.log.path=/Users/florian/Library/Logs/JetBrains/WebStorm2021.2

=== System ===
Number of CPU: 8
Used memory: 1264Mb 
Free memory: 485Mb 
Total memory: 1750Mb 
Maximum available memory: 2048Mb

=== Displays ===
Displays: 
Display 0: 2880x1800; scale: 2,00

=== Plugins ===
Custom plugins: [UUID Generator (4.5.1), .env files support (2021.3.0.212), Git Commit Template (1.2.0), Tailwind Formatter (1.4.2), MDX (1.2.212), JS GraphQL (3.0.0), Randomness (2.7.3), Cypress Support (1.4.1), Tailwind CSS Smart Completions (1.3.1)]
Disabled plugins:[]
```

**Comment by leomillon** [comment] 2021-10-12 10:13
That's really weird that I cannot reproduce this use case.

Just to be sure: did you (@lordigon and @nessor ) restart Intellij IDEA between the moment you upgraded the plugin and the moment you got this error? (because if you are using the "hot reload" feature from IDEA, that might be the difference between you and me 🤞 )

**Comment by nessor** [comment] 2021-10-12 10:44
No. I used the "hot reload" feature. But I didn't used the plugin at all. The error(s) appeared when WebStorm was complaining about a missing bracket.

Since I was closing WebStorm yesterday, I will have a look today or tomorrow if the error is still there.

**Comment by lordigon** [comment] 2021-10-12 11:50
I've uninstalled and installed the plugin again and the error is gone.
Thx for your support.

Il giorno mar 12 ott 2021 alle ore 12:45 Florian ***@***.***>
ha scritto:

**Comment by leomillon** [comment] 2021-10-12 11:58
Nice one!

For the tracking, I think this might be caused by the following modification on the plugin configuration that has been removed because flagged by the inspection as a "useless definition": https://github.com/leomillon/uuid-generator-plugin/commit/3794871f92d286bb7d092092fb4de76b39141bc2#diff-13198d14dd3abf13abd9cb906331ed7d9663fc081757b6845fd5f3c1850b5693L19

```xml
        <applicationService serviceInterface="com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings"
                            serviceImplementation="com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings"/>
```

`serviceInterface` == `serviceImplementation` so it became:
```xml
        <applicationService
                serviceImplementation="com.github.leomillon.uuidgenerator.settings.uuid.UUIDGeneratorSettings"/>
```

This might have caused the unexpected `ClassCastException` but I'm not 100% sure.

Anyway, sorry for the inconvenience, and thanks a lot for your feedback!

@nessor I'm waiting for your feedback to be sure that it's resolved for you as well before closing this issue.

**Comment by nessor** [comment] 2021-10-12 13:54
> I've uninstalled and installed the plugin again and the error is gone. Thx for your support. Il giorno mar 12 ott 2021 alle ore 12:45 Florian ***@***.***> ha scritto:
> […](#)

This worked for me also. Thanks @leomillon !

**Closed as completed** 2021-10-12 14:51 UTC
Labels: bug, wontfix
